
# First Run  the server `yarn start`
# First Run  prisma studio  `npx prisma studio`


# model AcademicSemester {
#   id         String    @id @default(uuid())
#   year       Int
#   title      String
#   code       String
#   startMonth String
#   endMonth   String
#   createdAt  DateTime  @default(now())
 

### Create Academic Semester
POST http://localhost:5001/api/v1/academic-semesters
Content-Type: application/json

{
    "year": 2027,
    "title": "Fall",
    "code": "03",
    "startMonth": "January",
    "endMonth": "April"
}

### Get All Academic Semesters
GET http://localhost:5001/api/v1/academic-semesters
Content-Type: application/json



#####################-------------##### for  pagination
### Get All Academic Semesters
GET http://localhost:5001/api/v1/academic-semesters?page=1&limit=2
Content-Type: application/json


##################-------------######## For filters
### filters
# GET http://localhost:5001/api/v1/academic-semesters?page=1&limit=10&searchTerm=fall&year=2023
# GET http://localhost:5001/api/v1/academic-semesters?page=1&limit=10&searchTerm=fall&code=03

# GET http://localhost:5001/api/v1/academic-semesters?page=1&limit=10&searchTerm=fall
# GET http://localhost:5001/api/v1/academic-semesters?page=1&limit=2&searchTerm=02 
# GET http://localhost:5001/api/v1/academic-semesters?page=1&limit=2&startMonth=January

### sortig data
# GET http://localhost:5001/api/v1/academic-semesters?page=1&limit=2
# GET http://localhost:5001/api/v1/academic-semesters?page=1&limit=2&sortBy=title
# GET http://localhost:5001/api/v1/academic-semesters?page=1&limit=2&sortBy=title&sortOrder=desc
GET http://localhost:5001/api/v1/academic-semesters?page=1&limit=2&sortBy=title&sortOrder=asc
Content-Type: application/json



### Get single semester by id
GET http://localhost:5001/api/v1/academic-semesters/189e2dce-073d-4a4b-ac31-2d99f8b70a28
Content-Type: application/json