
# First Run  the server `yarn start`
# First Run  prisma studio  `npx prisma studio`


# model AcademicSemester {
#   id         String    @id @default(uuid())
#   year       Int
#   title      String
#   code       String
#   startMonth String
#   endMonth   String
#   createdAt  DateTime  @default(now())
 

### Create Academic Semester
POST http://localhost:5001/api/v1/academic-semesters
Content-Type: application/json

{
    "year": 2023,
    "title": "Summer",
    "code": "02",
    "startMonth": "January",
    "endMonth": "April"
}

### Get All Academic Semesters
GET http://localhost:5001/api/v1/academic-semesters
Content-Type: application/json



# for filter and pagination
### Get All Academic Semesters
GET http://localhost:5001/api/v1/academic-semesters?page=1&limit=2
# GET http://localhost:5001/api/v1/academic-semesters?page=1&limit=10&searchTerm=fall&year=2023
Content-Type: application/json

